<? $this->load->view('site/header.phtml') ?>


<link rel="stylesheet" href="<?= site_url() ?>/application/views/common/fullcalendar-1.6.4/fullcalendar/fullcalendar.css" />
<script src="<?= site_url() ?>/application/views/common/fullcalendar-1.6.4/fullcalendar/fullcalendar.js"></script>

<script type="text/javascript" src="<?= site_url() ?>/application/views/site/calendar.js"></script>


<script type="text/javascript">
var DATA_SOURCES = <?= json_encode($sources) ?>;
</script>


<style type="text/css">
div.swatch {
    display:inline-block;
    width:1em;
    height:1em;
}
</style>


<div class="container" style="width:100%;">
    <div class="row">
        <div class="col-xs-8">
            <div id="calendar"></div>
        </div>
        <div class="col-xs-4">
            <br/>
            <br/>

            <?php foreach ($sources as $sourceid=>$info) { ?>
            <label><input type="checkbox" name="sources[]" <?= $info['checked'] ? 'checked' : '' ?> value="<?= $info['id'] ?>" /> <div class="swatch" style="background-color:<?= $info['bgcolor'] ?>;"></div> <?= htmlspecialchars($info['name']) ?></label>
            <br/>
            <?php } ?>

            <label><input type="checkbox" name="sources[]" checked value="0" /> <div class="swatch" style="background-color:#FFFFFF; border:1px solid #000000;"></div> Non-Event Activities</label>
        </div>
    </div>
</div>



<? $this->load->view('site/footer.phtml') ?>
