<!DOCTYPE html>
<html>
<head>
    <title><?= $this->siteconfig->get('title') ?></title>

    <!-- jQuery and jQuery UI -->
    <script type="text/javascript" src="<?= site_url() ?>/application/views/common/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="<?= site_url() ?>/application/views/common/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/common/jquery-ui-1.10.3/css/<?= $this->siteconfig->get('jquitheme') ?>/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/common/jquery-ui-1.10.3/css/<?= $this->siteconfig->get('jquitheme') ?>/customizations.css" />

    <!-- Twitter boostrap: mostly for responsive grid -->
    <!-- Warning: TB's JavaScript extensions don't play well with much else, e.g. borging JQUI's <button> tags; don't use it -->
    <link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/common/bootstrap-3.0.2/css/bootstrap.css" />
    <script type="text/javascript" src="<?= site_url() ?>/application/views/common/bootstrap-3.0.2/js/bootstrap.min.js"></script>
    <script type="text/javascript">
    // patch to make TB's button programming not mess with JQUI's button decoration
    var btn = $.fn.button.noConflict() // reverts $.fn.button to jqueryui btn
    $.fn.btn = btn // assigns bootstrap button functionality to $.fn.btn
    </script>

    <script type="text/javascript">
    var BASE_URL = <?= json_encode(site_url()) ?>;
    </script>

    <!-- sitewide styling overriding the selected theme and providing common code & style to the front-facing site -->
    <link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/common/website.css" />
    <script type="text/javascript" src="<?= site_url() ?>/application/views/site/site.js"></script>
</head>
<body>


<div class="navbar navbar-default navbar-static-top ui-widget-header" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?= site_url() ?>"><?= $this->siteconfig->get('title') ?></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!--
        <li id="navbar_map"><a href="<?= site_url('site') ?>">Link Here</a></li>
        -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!--
        <li><a href="<?= site_url('site/') ?>">Link Here</a></li>
        -->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


