<? $this->load->view('site/header.phtml') ?>

<form action="<?= current_url() ?>" method="post">
    <table style="margin:0.5in auto 0.5in auto;">
    <tr><td>Username</td><td><input type="text" name="username" /></td></tr>
    <tr><td>Password</td><td><input type="password" name="password" /></td></tr>
    <tr><td colspan="2"><input type="submit" value="Log In" style="width:100%;" /></td></tr>
    </table>
</form>

<? $this->load->view('site/footer.phtml') ?>
