<? $this->load->view('site/header.phtml') ?>

<!-- Leaflet map framework -->
<link rel="stylesheet" href="<?= site_url() ?>/application/views/common/leaflet-0.6.4/leaflet.css" />
<!--[if lte IE 8]>
<link rel="stylesheet" href="<?= site_url() ?>/application/views/common/leaflet-0.6.4/leaflet.ie.css" />
<![endif]-->
<script src="<?= site_url() ?>/application/views/common/leaflet-0.6.4/leaflet.js"></script>

<!-- a whole mess of basemap options for Leaflet: Google, Bing -->
<?php if ($siteconfig['google_api_key']) { ?>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&sensor=false&key=<?= $siteconfig['google_api_key'] ?>"></script>
<?php } else { ?>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&sensor=false"></script>
<?php } ?>
<script type="text/javascript" src="<?= site_url('application/views/common/leaflet.google.js') ?>"></script>
<script type="text/javascript" src="<?= site_url('application/views/common/leaflet.bing.js') ?>"></script>

<!-- marker clustering add-on for Leaflet then a label addon -->
<!--gda-->
<script src="<?= site_url() ?>/application/views/common/leaflet.prunecluster/PruneCluster.js"></script>
-<link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/common/leaflet.prunecluster/LeafletStyleSheet.css" />
<script src="<?= site_url() ?>/application/views/common/Leaflet.label-0.2.1/dist/leaflet.label.js"></script>
<!--<link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/common/Leaflet.label-0.2.1/dist/leaflet.label.css" />-->

<!-- other code specific to this page -->
<link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/site/map.css" />
<script type="text/javascript" src="<?= site_url() ?>/application/views/site/map.js"></script>
<script type="text/javascript">
var BASEMAP_TYPE   = <?= json_encode( $siteconfig['basemap_type'] ) ?>;
var BASEMAP_XYZURL = <?= json_encode( $siteconfig['basemap_xyzurl'] ) ?>;

var BING_API_KEY   = <?= json_encode( $siteconfig['bing_api_key'] ) ?>;
var GOOGLE_API_KEY = <?= json_encode( $siteconfig['google_api_key'] ) ?>;

var DISTANCE_UNITS = <?= json_encode( (integer) $siteconfig['metric_units'] ? 'km' : 'mi') ?>;

var START_W = <?= $this->siteconfig->get('bbox_w') ?>;
var START_S = <?= $this->siteconfig->get('bbox_s') ?>;
var START_E = <?= $this->siteconfig->get('bbox_e') ?>;
var START_N = <?= $this->siteconfig->get('bbox_n') ?>;

var BOTH_MARKER_WIDTH       = <?= $siteconfig['both_marker_width'] ?>;
var BOTH_MARKER_HEIGHT      = <?= $siteconfig['both_marker_height'] ?>;
var PLACE_MARKER_WIDTH      = <?= $siteconfig['place_marker_width'] ?>;
var PLACE_MARKER_HEIGHT     = <?= $siteconfig['place_marker_height'] ?>;
var EVENT_MARKER_WIDTH      = <?= $siteconfig['event_marker_width'] ?>;
var EVENT_MARKER_HEIGHT     = <?= $siteconfig['event_marker_height'] ?>;
</script>

<!-- GLOWING MARKERS if this gets more involved, probably best to put it into a separate CSS file -->
<style type="text/css">
img.leaflet-marker-icon.leaflet-marker-place.leaflet-marker-highlight {
    box-shadow: 0 0 8px 6px <?= $siteconfig['place_markerglowcolor'] ?> !important;
    background-color: <?= $siteconfig['place_markerglowcolor'] ?> !important;
    -webkit-box-shadow: 0 0 8px 6px <?= $siteconfig['place_markerglowcolor'] ?> !important;
    border-radius:10px;
}
img.leaflet-marker-icon.leaflet-marker-event.leaflet-marker-highlight {
    box-shadow: 0 0 8px 6px <?= $siteconfig['event_markerglowcolor'] ?> !important;
    background-color: <?= $siteconfig['event_markerglowcolor'] ?> !important;
    -webkit-box-shadow: 0 0 8px 6px <?= $siteconfig['event_markerglowcolor'] ?> !important;
    border-radius:10px;
}
</style>



<div class="container" style="padding: 0 15px 0 0; width:100%;">
    <div class="row" id="bigwrapper">
        <div class="col-xs-8" id="lhs">
            <div id="map_canvas"></div>
        </div>
        <div class="col-xs-4" id="rhs">
            <form id="tools">

                <h5>Zoom To Address</h5>
                <div>
                    <input type="text" id="geocode" style="width:75%" placeholder="Search for your address" /> <input type="button" id="geocode_go" value="Search" style="width:20%;" />
                    <br/>
                </div>

                <?php if ($has_event_locations) { ?>
                <h5>Events</h5>
                <div>
                    <label><input type="checkbox" name="event_locations" checked /> Show event locations</label>
                </div>
                <?php } ?>

                <h5>Filter by Categories</h5>
                <div>
                    <div style="float:right; font-size:75%;">
                        <a href="javascript:void(0);" class="check_all">all</a>
                        <br/>
                        <a href="javascript:void(0);" class="check_none">none</a>
                    </div>

                    <?php foreach ($categories as $catid=>$catinfo) { ?>
                    <label><input type="checkbox" name="categories[]" <?= $catinfo['checked'] ? 'checked' : '' ?> value="<?= $catid ?>" /> <?= htmlspecialchars($catinfo['name']) ?></label><br/>
                    <?php } ?>
                </div>

                <h5>Filter by Keywords</h5>
                <div>
                    Filter places by searching for keywords:<br/>
                    <input type="text" name="keywords" style="width:50%" placeholder="Enter keywords" /> <input type="button" class="search_submit" value="Search" style="width:20%;" />
                    &nbsp;
                    <a href="javascript:void(0);" id="keywords_clear">clear</a>
                </div>

                <h5>Filter by Date</h5>
                <div>
                    Show places with activities listed on this date:<br/>
                    <input type="text" class="dateinput" name="date" style="width:100px;" /> <input type="button" class="search_submit" value="Search" />
                    &nbsp;
                    <a href="javascript:void(0);" id="datetime_now">today</a>
                    &nbsp;
                    <a href="javascript:void(0);" id="datetime_clear">clear</a>
                </div>

            </form>
        </div>
    </div>
</div>



<div class="dialog" id="dialog_directions">
<form action="javascript:void(0);">
    <input type="hidden" name="lat" id="directions_lat" />
    <input type="hidden" name="lon" id="directions_lon" />

    To:<br/>
    <span id="directions_destname"></span><br/>
    <br/>

    From:<br/>
    <input type="text" namne="address" id="directions_address" style="width:3in;" placeholder="Starting address" /><br/>
    <br/>

    <div id="directions_results"></div>
</form>
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>


<? $this->load->view('site/footer.phtml') ?>
