<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/event_sources.js"></script>
<style type="text/css">
.swatch {
    height:1.5em;
    width:2.25em;
    display:inline-block;
}
.refresh {
    cursor:pointer;
}
</style>


<div class="tabs container" style="width:100%; padding:0;">
    <ul>
        <li><a href="#tab_sources">Sources</a></li>
    </ul>
    <div id="tab_sources">

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_new"><span class="glyphicon glyphicon-certificate"></span> New</button>
        </div>

        <p>
            The application displays events loaded from the sources listed here. Only events from <i>Enabled</i> sources will be displayed on the site.
        </p>

        <table id="sources" class="table table-condensed table-bordered sortable">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th># Events</th>
            <th>Enabled?</th>
            <th>Last Fetch</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sources as $source) { ?>
        <tr data-source-id="<?= $source->id ?>" data-source-name="<?= htmlspecialchars($source->name) ?>" data-source-enabled="<?= (integer) $source->enabled ?>">
            <td>
                <div class="swatch" title="Color sample" style="background-color:<?= htmlspecialchars($source->bgcolor) ?>; color:<?= htmlspecialchars($source->color) ?>;">&nbsp;Aa</div>
                <a href="<?= site_url("administration/event_source/{$source->id}") ?>"><?= htmlspecialchars($source->name) ?></a>
            </td>
            <td><?= $source->type ?></td>
            <td><?= $source->howManyEvents() ?></td>
            <td><?= $source->enabled ? 'Enabled' : 'Disabled' ?></td>
            <td><span class="glyphicon glyphicon-refresh refresh" title="Fetch now"></span> <?= $source->lastFetch() ?></td>
        </tr>
        <?php } ?>
        </tbody>
        </table>

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_reload_sources"><span class="glyphicon glyphicon-repeat"></span> Reload All</button>
        </div>

    </div>
</div>




<div class="dialog" id="dialog_new">
<form action="javascript:void(0);">
    <table>
    <tr>
        <td>Name</td>
        <td><input type="text" name="name" maxlength="50" style="width:3in;" placeholder="A name for this data source" /></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><?= form_dropdown('type', $types) ?></td>
    </tr>
    </table>
</form>
</div>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>


<? $this->load->view('administration/footer.phtml') ?>
