<? $this->load->view('administration/header.phtml') ?>

<link rel="stylesheet" media="screen" type="text/css" href="<?= site_url() ?>/application/views/common/colorpicker/css/colorpicker.css" />
<script type="text/javascript" src="<?= site_url() ?>/application/views/common/colorpicker/js/colorpicker.js"></script>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/event_source.js"></script>

<script type="text/javascript">
var SOURCE_TYPE = <?= json_encode($source->type) ?>;
</script>

<style type="text/css">
em {
    font-size:75%;
}
</style>


<div class="container">
    <br/>

    <form action="javascript:void(0);" id="editform">
    <input type="hidden" name="id" value="<?= $source->id ?>" />
    <input type="hidden" name="type" value="<?= $source->type ?>" />
    <table class="table-condensed table-bordered">
        <tr>
            <td>Type</td>
            <td><?= htmlspecialchars($source->type) ?></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text" name="name" value="<?= htmlspecialchars($source->name) ?>" size="50" maxlength="50" /></td>
        </tr>
        <tr>
            <td>Enabled?</td>
            <td>
                <?= form_dropdown('enabled', array('1'=>'Enabled', '0'=>'Disabled'),$source->enabled) ?>
                <br/>
                If disabled, this data source will not appear on the Calendar page, and will not be refreshed automatically.
            </td>
        </tr>
        <tr>
            <td>On by default?</td>
            <td>
                <?= form_dropdown('on_by_default', array('1'=>'Yes', '0'=>'No'),$source->on_by_default) ?>
                <br/>
                On the Calendar page, should these events be visible (checked) when the page loads?
            </td>
        </tr>
        <tr>
            <td>Text Color</td>
            <td>
                <input type="text" name="color" value="<?= htmlspecialchars($source->color) ?>" size="7" maxlength="7" style="color:white;" />
                When these events are displayed on the Calendar page, this color will be used for the event's text.
            </td>
        </tr>
        <tr>
            <td>Background Color</td>
            <td>
                <input type="text" name="bgcolor" value="<?= htmlspecialchars($source->bgcolor) ?>" size="7" maxlength="7" style="color:white;" />
                When these events are displayed on the Calendar page, this color will be used for the event's background.
            </td>
        </tr>

        <?php if ($source->option_fields['url']) { ?>
        <tr>
            <td><?= $source->option_fields['url']['name'] ?></td>
            <td>
                <input type="text" name="url" value="<?= $source->url ?>" size="100" maxlength="500" />
                <br/>
                <em><?= $source->option_fields['url']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option1']) { ?>
        <tr>
            <td><?= $source->option_fields['option1']['name'] ?></td>
            <td>
                <input type="text" name="option1" value="<?= $source->option1 ?>" size="100" maxlength="500" />
                <br/>
                <em><?= $source->option_fields['option1']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option2']) { ?>
        <tr>
            <td><?= $source->option_fields['option2']['name'] ?></td>
            <td>
                <input type="text" name="option2" value="<?= $source->option2 ?>" size="100" maxlength="500" />
                <br/>
                <em><?= $source->option_fields['option2']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option3']) { ?>
        <tr>
            <td><?= $source->option_fields['option3']['name'] ?></td>
            <td>
                <input type="text" name="option3" value="<?= $source->option3 ?>" size="100" maxlength="500" />
                <br/>
                <em><?= $source->option_fields['option3']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option4']) { ?>
        <tr>
            <td><?= $source->option_fields['option4']['name'] ?></td>
            <td>
                <input type="text" name="option4" value="<?= $source->option4 ?>" size="100" maxlength="500" />
                <br/>
                <em><?= $source->option_fields['option4']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td></td>
            <td>
                <div class="btn-group">
                <button type="button" class="btn ui-state-focus" id="button_save"><span class="glyphicon glyphicon-thumbs-up"></span> Save and Exit</button>
                <button type="button" class="btn ui-state-focus" id="button_fetch"><span class="glyphicon glyphicon-transfer"></span> Save and Fetch</button>
                </div>
            </td>
        </tr>
    </table>
    </form>

</div>



<form action="<?= site_url('administration/event_source_delete') ?>" method="post" style="text-align:right;">
    <input type="hidden" name="id" value="<?= $source->id ?>" />
    <div class="btn-group">
        <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-trash"></span> Delete</button>
    </div>
</form>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>


<? $this->load->view('administration/footer.phtml') ?>
