<? $this->load->view('administration/header.phtml') ?>

<div class="float_right">
    <img src="<?= site_url('application/views/images/GetOutside_Screenshot_Home.png') ?>" title="Mobile home screenshot">
        <br />
    <img src="<?= site_url('application/views/images/GetOutside_Screenshot_Map.png') ?>"  title="Mobile map screenshot">
</div>

<div class="container">
    <h2 class="brand-heading">Get Outside</h2>
    
    <p>Using the GetOutside tool, cities can quickly launch a fully-designed, ready to use <a href="http://websites.greeninfo.org/knight/getoutside/stpaul1/mobile" target="_blank">mobile park and recreation event finder</a> that anyone can use to find nearby parks and events.</p>
    
    <br><h4>How It Works</h4>
    
    <p>Get Outside aggregates your parks and events data and displays it in a searchable mobile application.  The tool is designed to link directly with your existing data such as Google Spreadsheets, Google Calendar, GIS map services... </p>
    
    <p>Get Outside works with the following types of data: <br />
        <div class="indent">
           <b>Places</b> - Parks and recreation centers, along with amentity information <br />
           <b>Events</b> - Events occuring on a specific day
        </div>
    </p>

   <h4>Getting Started</h4>
    <ol class="boxes-list">
        <li><b>Add Places</b> <br />
                First, set up search categories (baseball, bbq grills...)             
             <div class="indent"><i>Click on Places, then Categories. Click on New. </i></div>

                    <br />  Next, add parks data <br />
             <div class="indent"><i>Click on Places, then Sources. Click on New.  Follow prompts to add your data.</i> <br>
                    Note: To create parks data from scratch, you can use this <a target="_blank" href="https://docs.google.com/spreadsheets/d/1e4rbpYv8KNAKrsCilHcxjaqhtpx4osgfYRAtqNCp0fI/pubhtml#">Google Spreadsheet example </a> as a guide.
             </div>
        
        </li>
        <li><b>Add Events</b> <p>Define data sources from which events will be loaded.</p></li>
        <li><b>Customize Your Application</b> <p>Add your logo, choose colors and map icons. <br>
            Click on <b>Settings</b> and explore options within each of the categories: Map Services, Map Icons, Mobile Site.  </p>
        </li>
        
        <li><b>Add Users</b> <p>Decide who can use this administration panel.</p></li>
    </ol>
</div>


<? $this->load->view('administration/footer.phtml') ?>
