<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/place_sources.js"></script>
<style type="text/css">
.swatch {
    display:inline-block;

    height:14px;
    width:14px;

    border:1px solid black;
    border-radius:7px;
}
.refresh {
    cursor:pointer;
}
</style>



<div class="tabs container">
    <ul>
        <li><a href="#tab_categories">Categories</a></li>
        <li><a href="#tab_sources">Sources</a></li>
    </ul>
    <div id="tab_categories">

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_new_category"><span class="glyphicon glyphicon-certificate"></span> New</button>
        </div>

        <p>
            This defines the list of categories which will be displayed on the Map page. The <i>Enabled</i> categories will be displayed as a set of checkboxes, allowing visitors to filter the places shown on the map.
            Places may belong to multiple categories, such as <i>Parks</i> and also <i>Basketball</i>.
            Categories and sources are related: a source is used to load places into the database, and these places are categorized so they show up when filters are selected.
        </p>

        <table class="table table-condensed table-bordered sortable">
        <thead>
        <tr>
            <th>Name</th>
            <th># Places</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($categories as $category) { ?>
        <tr>
            <td>
                <a href="<?= site_url("administration/place_category/{$category->id}") ?>"><?= htmlspecialchars($category->name) ?></a>
            </td>
            <td><?= $category->howManyPlaces() ?></td>
            <td><?= (integer) $category->enabled ? 'Enabled' : 'Disabled' ?></td>
        </tr>
        <?php } ?>
        </tbody>
        </table>

    </div>
    <div id="tab_sources">

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_new_source"><span class="glyphicon glyphicon-certificate"></span> New</button>
        </div>

        <p>
            The locations shown on the Map page are loaded from the sources listed here.
            A data source is a web service such as a Google Spreadsheet, with a set of rules indicating how to treat the features as they are loaded.
            For instance, you can define rules that will automatically add categories to each place depending on its fields.
        </p>

        <table class="table table-condensed table-bordered sortable">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th># Places</th>
            <th>Status</th>
            <th>Last Fetch</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sources as $source) { ?>
        <tr>
            <td>
                <a href="<?= site_url("administration/place_source/{$source->id}") ?>"><?= htmlspecialchars($source->name) ?></a>
            </td>
            <td><?= $source->type ?></td>
            <td><?= $source->howManyPlaces() ?></td>
            <td><?= (integer) $source->enabled ? 'Enabled' : 'Disabled' ?></td>
            <td><span class="glyphicon glyphicon-refresh refresh" data-id="<?= $source->id ?>" title="Fetch now"></span> <?= $source->lastFetch() ?></td>
        </tr>
        <?php } ?>
        </tbody>
        </table>

    </div>
</div>




<div class="dialog" id="dialog_new_category">
<form action="javascript:void(0);">
    Enter a name for the category:<br/>
    <td><input type="text" name="name" maxlength="50" style="width:3in;" placeholder="A name for this category" /></td>
</form>
</div>



<div class="dialog" id="dialog_new_source">
<form action="javascript:void(0);">
    <table>
    <tr>
        <td>Name</td>
        <td><input type="text" name="name" maxlength="50" style="width:3in;" placeholder="A name for this data source" /></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><?= form_dropdown('type', $types) ?></td>
    </tr>
    </table>
</form>
</div>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>

<? $this->load->view('administration/footer.phtml') ?>
