<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/place_category.js"></script>

<style type="text/css">
em {
    font-size:75%;
}
</style>



<div class="container">
    <br/>

    <form action="javascript:void(0);" id="editform">
    <input type="hidden" name="id" value="<?= $category->id ?>" />
    <input type="hidden" name="type" value="<?= $category->type ?>" />
    <table class="table-condensed table-bordered">

        <!-- if there's an alert, put it here. inside the table, so it has the right width -->
        <?php if (@$warning) { ?>
        <tr>
        <td colspan="2"><div class="alert alert-danger"> &nbsp; <?= htmlspecialchars($warning) ?></div></td>
        </tr>
        <?php } ?>

        <tr>
            <td>Name</td>
            <td><input type="text" name="name" value="<?= htmlspecialchars($category->name) ?>" size="50" maxlength="50" /></td>
        </tr>

        <!-- DONE -->
        <tr>
            <td></td>
            <td>
                <div class="btn-group">
                <button type="button" class="btn ui-state-focus" id="button_save"><span class="glyphicon glyphicon-thumbs-up"></span> Save Changes</button>
                </div>
            </td>
        </tr>
    </table>
    </form>

</div>



<form action="<?= site_url('administration/place_category_delete') ?>" method="post" style="text-align:right;">
    <input type="hidden" name="id" value="<?= $category->id ?>" />
    <div class="btn-group">
        <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-trash"></span> Delete</button>
    </div>
</form>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<? $this->load->view('administration/footer.phtml') ?>
