<? $this->load->view('administration/header.phtml') ?>

<link rel="stylesheet" media="screen" type="text/css" href="<?= site_url() ?>/application/views/common/colorpicker/css/colorpicker.css" />
<script type="text/javascript" src="<?= site_url() ?>/application/views/common/colorpicker/js/colorpicker.js"></script>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/place_source.js"></script>

<script type="text/javascript">
var SOURCE_TYPE = <?= json_encode($source->type) ?>;
</script>

<style type="text/css">
em {
    font-size:75%;
}
</style>



<div class="container">
    <br/>

    <form action="javascript:void(0);" id="editform">
    <input type="hidden" name="id" value="<?= $source->id ?>" />
    <input type="hidden" name="type" value="<?= $source->type ?>" />
    <table class="table-condensed table-bordered">

        <!-- if there's an alert, put it here. inside the table, so it has the right width -->
        <?php if (@$warning) { ?>
        <tr>
        <td colspan="2"><div class="alert alert-danger"> &nbsp; <?= htmlspecialchars($warning) ?></div></td>
        </tr>
        <?php } ?>

        <tr>
            <td>Type</td>
            <td><?= htmlspecialchars($source->type) ?></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text" name="name" value="<?= htmlspecialchars($source->name) ?>" size="50" maxlength="50" /></td>
        </tr>

        <?php if ($source->option_fields['url']) { ?>
        <tr>
            <td><?= $source->option_fields['url']['name'] ?></td>
            <td>
                <input type="text" name="url" value="<?= $source->url ?>" size="100" maxlength="500" />
                <br/>
                <em><?= $source->option_fields['url']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option1']) { ?>
        <tr>
            <td><?= $source->option_fields['option1']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option1']['isfield'] and $fields and is_array($fields)) { ?>
                    <?= form_dropdown('option1',$fields,$source->option1) ?>
                <?php } else { ?>
                    <input type="text" name="option1" value="<?= $source->option1 ?>" size="100" maxlength="500" />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option1']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option2']) { ?>
        <tr>
            <td><?= $source->option_fields['option2']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option2']['isfield'] and $fields and is_array($fields)) { ?>
                    <?= form_dropdown('option2',$fields,$source->option2) ?>
                <?php } else { ?>
                    <input type="text" name="option2" value="<?= $source->option2 ?>" size="100" maxlength="500" />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option2']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option3']) { ?>
        <tr>
            <td><?= $source->option_fields['option3']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option3']['isfield'] and $fields and is_array($fields)) { ?>
                    <?= form_dropdown('option3',$fields,$source->option3) ?>
                <?php } else { ?>
                    <input type="text" name="option3" value="<?= $source->option3 ?>" size="100" maxlength="500" />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option3']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option4']) { ?>
        <tr>
            <td><?= $source->option_fields['option4']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option4']['isfield'] and $fields and is_array($fields)) { ?>
                    <?= form_dropdown('option4',$fields,$source->option4) ?>
                <?php } else { ?>
                    <input type="text" name="option4" value="<?= $source->option4 ?>" size="100" maxlength="500" />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option4']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>

        <tr>
            <td>Automatic Categorization</td>
            <td>
                <p>
                    Places loaded from this data source can be automatically categorized by matching a field and value, for example <i>Swimming=Yes</i>
                    <br/>
                    <i>All matching rules will be used, so a place may be assigned multiple categories.</i>
                    <br/>
                    &bull; A blank rule will skip that category. Use this if you don't want any places in this source to fit that category.
                    <br/>
                    &bull; The "ALL RECORDS" rule will match all places loaded from this source. Use this if all places should be in the same category, e.g. &quot;County Parks&quot;.
                </p>

                <?php foreach ($categories as $category) { ?>
                <div class="row">
                    <div class="col-md-4">
                        <?= htmlspecialchars($category->name) ?>
                    </div>
                    <div class="col-md-8">
                        <?= form_dropdown("categorization[{$category->id}][field]", $rule_fields, $rules[$category->id]['field'], "style=\"max-width:50%;\"") ?>
                        =
                        <input type="text" name="categorization[<?= $category->id ?>][value]" value="<?= @$rules[$category->id]['value'] ?>" style="width:40%;" />
                    </div>
                </div>
                <?php } ?>

            </td>
        </tr>


        <!-- DONE -->
        <tr>
            <td></td>
            <td>
                <div class="btn-group">
                <button type="button" class="btn ui-state-focus" id="button_save"><span class="glyphicon glyphicon-thumbs-up"></span> Save and Exit</button>
                <button type="button" class="btn ui-state-focus" id="button_fetch"><span class="glyphicon glyphicon-transfer"></span> Save and Fetch</button>
                </div>
            </td>
        </tr>
    </table>
    </form>

</div>



<form action="<?= site_url('administration/place_source_delete') ?>" method="post" style="text-align:right;">
    <input type="hidden" name="id" value="<?= $source->id ?>" />
    <div class="btn-group">
        <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-trash"></span> Delete</button>
    </div>
</form>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>


<? $this->load->view('administration/footer.phtml') ?>
