<? $this->load->view('administration/header.phtml') ?>

<link rel="stylesheet" media="screen" type="text/css" href="<?= site_url() ?>/application/views/common/colorpicker/css/colorpicker.css" />
<script type="text/javascript" src="<?= site_url() ?>/application/views/common/colorpicker/js/colorpicker.js"></script>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/place_source.js"></script>

<script type="text/javascript">
var SOURCE_TYPE = <?= json_encode($source->type) ?>;
</script>

<style type="text/css">
em {
    font-size:75%;
}

#dialog_loadok div {
    white-space:pre;
}
#dialog_loadok_details {
    display:none;
}
#dialog_loadok_details_toggle {
    font-weight:bold;
    cursor:pointer;
    text-decoration:underline;
}
</style>



<div class="container">
    <br/>

    <form action="javascript:void(0);" id="editform">
    <input type="hidden" name="id" value="<?= $source->id ?>" />
    <input type="hidden" name="type" value="<?= $source->type ?>" />
    <table class="table-condensed table-bordered">

        <!-- if there's an alert, put it here. inside the table, so it has the right width -->
        <?php if (@$warning) { ?>
        <tr>
        <td colspan="2"><div class="alert alert-danger"> &nbsp; <?= htmlspecialchars($warning) ?></div></td>
        </tr>
        <?php } ?>

        <tr>
            <td>Type</td>
            <td><?= htmlspecialchars($source->type) ?></td>
        </tr>
        <tr>
            <td>Name</td>
            <td><input type="text" name="name" value="<?= htmlspecialchars($source->name) ?>" size="50" maxlength="50" /></td>
        </tr>
        <tr>
            <td>Enabled?</td>
            <td>
                <?= form_dropdown('enabled', array('1'=>'Enabled', '0'=>'Disabled'),$source->enabled) ?>
                <br/>
                If disabled, this data source will not be reloaded when you use Reload All. This is useful if the data source is down for maintenance or is a work in progress.
            </td>
        </tr>

        <?php if ($source->option_fields['url']) { ?>
        <tr>
            <td><?= $source->option_fields['url']['name'] ?></td>
            <td>
                <input type="text" name="url" value="<?= $source->url ?>" size="100" maxlength="500" required />
                <br/>
                <em><?= $source->option_fields['url']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option1']) { ?>
        <tr>
            <td><?= $source->option_fields['option1']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option1']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option1']['required']) { ?>
                        <?= form_dropdown('option1',$required_fields,$source->option1) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option1',$optional_fields,$source->option1) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option1" value="<?= $source->option1 ?>" size="<?= @$source->option_fields['option1']['maxlength'] ? (integer) $source->option_fields['option1']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option1']['maxlength'] ? (integer) $source->option_fields['option1']['maxlength'] : 100 ?>" <?= $source->option_fields['option1']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option1']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option2']) { ?>
        <tr>
            <td><?= $source->option_fields['option2']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option2']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option2']['required']) { ?>
                        <?= form_dropdown('option2',$required_fields,$source->option2) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option2',$optional_fields,$source->option2) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option2" value="<?= $source->option2 ?>" size="<?= @$source->option_fields['option2']['maxlength'] ? (integer) $source->option_fields['option2']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option2']['maxlength'] ? (integer) $source->option_fields['option2']['maxlength'] : 100 ?>" <?= $source->option_fields['option2']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option2']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option3']) { ?>
        <tr>
            <td><?= $source->option_fields['option3']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option3']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option3']['required']) { ?>
                        <?= form_dropdown('option3',$required_fields,$source->option3) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option3',$optional_fields,$source->option3) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option3" value="<?= $source->option3 ?>" size="<?= @$source->option_fields['option3']['maxlength'] ? (integer) $source->option_fields['option3']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option3']['maxlength'] ? (integer) $source->option_fields['option3']['maxlength'] : 100 ?>" <?= $source->option_fields['option3']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option3']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option4']) { ?>
        <tr>
            <td><?= $source->option_fields['option4']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option4']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option4']['required']) { ?>
                        <?= form_dropdown('option4',$required_fields,$source->option4) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option4',$optional_fields,$source->option4) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option4" value="<?= $source->option4 ?>" size="<?= @$source->option_fields['option4']['maxlength'] ? (integer) $source->option_fields['option4']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option4']['maxlength'] ? (integer) $source->option_fields['option4']['maxlength'] : 100 ?>" <?= $source->option_fields['option4']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option4']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option5']) { ?>
        <tr>
            <td><?= $source->option_fields['option5']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option5']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option5']['required']) { ?>
                        <?= form_dropdown('option5',$required_fields,$source->option5) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option5',$optional_fields,$source->option5) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option5" value="<?= $source->option5 ?>" size="<?= @$source->option_fields['option5']['maxlength'] ? (integer) $source->option_fields['option5']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option5']['maxlength'] ? (integer) $source->option_fields['option5']['maxlength'] : 100 ?>" <?= $source->option_fields['option5']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option5']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option6']) { ?>
        <tr>
            <td><?= $source->option_fields['option6']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option6']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option6']['required']) { ?>
                        <?= form_dropdown('option6',$required_fields,$source->option6) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option6',$optional_fields,$source->option6) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option6" value="<?= $source->option6 ?>" size="<?= @$source->option_fields['option6']['maxlength'] ? (integer) $source->option_fields['option6']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option6']['maxlength'] ? (integer) $source->option_fields['option6']['maxlength'] : 100 ?>" <?= $source->option_fields['option6']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option6']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option7']) { ?>
        <tr>
            <td><?= $source->option_fields['option7']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option7']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option7']['required']) { ?>
                        <?= form_dropdown('option7',$required_fields,$source->option7) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option7',$optional_fields,$source->option7) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option7" value="<?= $source->option7 ?>" size="<?= @$source->option_fields['option7']['maxlength'] ? (integer) $source->option_fields['option7']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option7']['maxlength'] ? (integer) $source->option_fields['option7']['maxlength'] : 100 ?>" <?= $source->option_fields['option7']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option7']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option8']) { ?>
        <tr>
            <td><?= $source->option_fields['option8']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option8']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option8']['required']) { ?>
                        <?= form_dropdown('option8',$required_fields,$source->option8) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option8',$optional_fields,$source->option8) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option8" value="<?= $source->option8 ?>" size="<?= @$source->option_fields['option8']['maxlength'] ? (integer) $source->option_fields['option8']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option8']['maxlength'] ? (integer) $source->option_fields['option8']['maxlength'] : 100 ?>" <?= $source->option_fields['option8']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option8']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>
        <?php if ($source->option_fields['option9']) { ?>
        <tr>
            <td><?= $source->option_fields['option9']['name'] ?></td>
            <td>
                <?php if (@$source->option_fields['option9']['isfield'] and $required_fields and is_array($required_fields)) { ?>
                    <?php if ($source->option_fields['option9']['required']) { ?>
                        <?= form_dropdown('option9',$required_fields,$source->option9) ?>
                    <?php } else { ?>
                        <?= form_dropdown('option9',$optional_fields,$source->option9) ?>
                    <?php } ?>
                <?php } else { ?>
                    <input type="text" name="option9" value="<?= $source->option9 ?>" size="<?= @$source->option_fields['option9']['maxlength'] ? (integer) $source->option_fields['option9']['maxlength'] : 100 ?>" maxlength="<?= @$source->option_fields['option9']['maxlength'] ? (integer) $source->option_fields['option9']['maxlength'] : 100 ?>" <?= $source->option_fields['option9']['required'] ? 'required' : '' ?> />
                <?php } ?>
                <br/>
                <em><?= $source->option_fields['option9']['help'] ?></em>
            </td>
        </tr>
        <?php } ?>

        <tr style="<?= $rule_fields ? '' : 'display:none;' ?>">
            <td>Automatic Categorization</td>
            <td>
                <p>
                    Places loaded from this data source can be automatically categorized by matching a field and value, for example <i>Swimming=Yes</i>
                    <br/>
                    <i>All matching rules will be used, so a place may be assigned multiple categories.</i>
                    <br/>
                    &bull; A blank rule will skip that category. Use this if you don't want any places in this source to fit that category.
                    <br/>
                    &bull; The "ALL RECORDS" rule will match all places loaded from this source. Use this if all places should be in the same category, e.g. &quot;County Parks&quot;.
                </p>

                <?php foreach ($categories as $category) { ?>
                <div class="row">
                    <div class="col-md-4">
                        <?= htmlspecialchars($category->name) ?>
                    </div>
                    <div class="col-md-8">
                        <?= form_dropdown("categorization[{$category->id}][field]", @$rule_fields, @$rules[$category->id]['field'], "style=\"max-width:50%;\"") ?>
                        =
                        <input type="text" name="categorization[<?= $category->id ?>][value]" value="<?= @$rules[$category->id]['value'] ?>" style="width:40%;" />
                    </div>
                </div>
                <?php } ?>

            </td>
        </tr>


        <!-- DONE -->
        <tr>
            <td></td>
            <td>
                <div class="btn-group">
                <button type="button" class="btn ui-state-focus" id="button_save"><span class="glyphicon glyphicon-thumbs-up"></span> Save and Exit</button>
                <button type="button" class="btn ui-state-focus" id="button_fetch"><span class="glyphicon glyphicon-transfer"></span> Save and Fetch</button>
                </div>
            </td>
        </tr>
    </table>
    </form>

</div>



<form action="<?= site_url('administration/place_source_delete') ?>" method="post" style="text-align:right;">
    <input type="hidden" name="id" value="<?= $source->id ?>" />
    <div class="btn-group">
        <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-trash"></span> Delete</button>
    </div>
</form>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>


<div class="dialog" id="dialog_loadok">
    <div id="dialog_loadok_summary"></div>
    <br/>

    <span id="dialog_loadok_details_toggle">Show details</span><br/>
    <div id="dialog_loadok_details"></div>
    <br/>
</div>


<? $this->load->view('administration/footer.phtml') ?>
