<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/place_sources.js"></script>
<style type="text/css">
.swatch {
    display:inline-block;

    height:14px;
    width:14px;

    border:1px solid black;
    border-radius:7px;
}
.refresh {
    cursor:pointer;
}
</style>



<div class="tabs container" style="width:100%; padding:0;">
    <ul>
        <li><a href="#tab_sources">Sources</a></li>
        <li><a href="#tab_categories">Categories</a></li>
        <li><a href="#tab_places">Places</a></li>
    </ul>
    <div id="tab_sources">

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_new_source"><span class="glyphicon glyphicon-certificate"></span> New</button>
        </div>

        <p>
            Parks and Recreation centers displayed in the mobile application are loaded from the data sources listed here. You can load your data from a Google Spreadsheet, formatted like this <a href="https://docs.google.com/spreadsheets/d/1e4rbpYv8KNAKrsCilHcxjaqhtpx4osgfYRAtqNCp0fI/pubhtml#" target="_blank">one</a>, or use a GIS web service if your city has one. To start, click <b>New</b> and set up a new data source.
            <br />
            <i>Tip: Before adding a data source, go to the categories tab to set up the park search options.</i>
        </p>

        <table id="sources" class="table table-condensed table-bordered sortable">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th># Places</th>
            <th>Enabled?</th>
            <th>Last Fetch</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sources as $source) { ?>
        <tr data-source-id="<?= $source->id ?>" data-source-name="<?= htmlspecialchars($source->name) ?>" data-source-enabled="<?= (integer) $source->enabled ?>">
            <td>
                <a href="<?= site_url("administration/place_source/{$source->id}") ?>"><?= htmlspecialchars($source->name) ?></a>
            </td>
            <td><?= $source->type ?></td>
            <td><?= $source->howManyPlaces() ?></td>
            <td><?= $source->enabled ? 'Enabled' : 'Disabled' ?></td>
            <td><span class="glyphicon glyphicon-refresh refresh" title="Fetch now"></span> <?= $source->lastFetch() ?></td>
        </tr>
        <?php } ?>
        </tbody>
        </table>

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_reload_sources"><span class="glyphicon glyphicon-repeat"></span> Reload All</button>
        </div>

    </div>

    <div id="tab_categories">

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_new_category"><span class="glyphicon glyphicon-certificate"></span> New</button>
        </div>

        <p>
            To enable users to search for parks and recreation centers that have specific amenities such as baseball fields, bbq grills, or playareas, add the desired search categories to this list. Click <b>New</b> to create a new category.
            <br/>
            Next, go to the Sources tab and open up a Place source, to link the categories with the data.
        </p>

        <table class="table table-condensed table-bordered sortable">
        <thead>
        <tr>
            <th>Name</th>
            <th># Places</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($categories as $category) { ?>
        <tr>
            <td>
                <a href="<?= site_url("administration/place_category/{$category->id}") ?>"><?= htmlspecialchars($category->name) ?></a>
            </td>
            <td><?= $category->howManyPlaces() ?></td>
            <td><?= (integer) $category->enabled ? 'Enabled' : 'Disabled' ?></td>
        </tr>
        <?php } ?>
        </tbody>
        </table>

    </div>

    <div id="tab_places">
        <p>
            These locations have been loaded into the database for display on the site. Use these filters for data review and testing.
        </p>


        <p>
            Filter:
            <?= form_dropdown('places_filter_source', $places_filter_source_options, $this->session->userdata('admin_places_filter_source') ) ?>
            <?= form_dropdown('places_filter_category', $places_filter_category_options, $this->session->userdata('admin_places_filter_category')) ?>
        </p>

        <table id="places_list" class="table table-condensed table-bordered sortable">
        <thead>
        <tr>
            <th>Name</th>
            <th>Source</th>
            <th>Categories</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($places as $place) { ?>
        <tr data-source-id="<?= $place->placedatasource->id ?>" data-category-ids="<?= $place->listCategoryIDs(',') ?>">
            <td>
                <a href="<?= site_url("administration/place/{$place->id}") ?>"><?= htmlspecialchars($place->name) ?></a>
                <br/>
                <!--<a target="_blank" href="<?= site_url("site/place/{$place->id}") ?>">(public view)</a>-->
            </td>
            <td>
                <?= htmlspecialchars($place->placedatasource->name) ?>
            </td>
            <td>
                <?= htmlspecialchars($place->listCategoryNames(', ')) ?>
            </td>
        </tr>
        <?php } ?>
        </tbody>
        </table>

    </div>

</div>




<div class="dialog" id="dialog_new_category">
<form action="javascript:void(0);">
    Enter a name for the category:<br/>
    <td><input type="text" name="name" maxlength="50" style="width:3in;" placeholder="A name for this category" /></td>
</form>
</div>



<div class="dialog" id="dialog_new_source">
<form action="javascript:void(0);">
    <table>
    <tr>
        <td>Name</td>
        <td><input type="text" name="name" maxlength="50" style="width:3in;" placeholder="A name for this data source" /></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><?= form_dropdown('type', $types) ?></td>
    </tr>
    </table>
</form>
</div>



<div class="dialog" id="dialog_fetching">
    This can take a few minutes.
    <br/>
    Please be patient.
</div>


<div class="dialog" id="dialog_waiting">
    One moment please.
    <br/>
</div>

<? $this->load->view('administration/footer.phtml') ?>
