<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript">
$(document).ready(function () {
    // pick the navbar entry to show where we are
    $('#navbar_place_sources').addClass('ui-state-focus');
});
</script>


<div class="container">
<br/>

    <form action="<?= current_url() ?>" method="post" id="deleteform">
    <input type="hidden" name="id" value="<?= $category->id ?>" />
        <p>Really delete <b><?= $category->name ?></b> ?</p>
        <div class="btn-group">
        <button type="submit" name="ok" value="ok" class="btn ui-state-focus"><span class="glyphicon glyphicon-trash"></span> Confirm Deletion</button>
        </div>
    </form>

<br/>
</div>

<? $this->load->view('administration/footer.phtml') ?>
