<? $this->load->view('administration/header.phtml') ?>

<!-- Leaflet map framework -->
<link rel="stylesheet" href="<?= site_url() ?>/application/views/common/leaflet-0.6.4/leaflet.css" />
<!--[if lte IE 8]>
<link rel="stylesheet" href="<?= site_url() ?>/application/views/common/leaflet-0.6.4/leaflet.ie.css" />
<![endif]-->
<script src="<?= site_url() ?>/application/views/common/leaflet-0.6.4/leaflet.js"></script>

<!-- a whole mess of basemap options for Leaflet: Google, Bing -->
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&sensor=false"></script>
<script type="text/javascript" src="<?= site_url('application/views/common/leaflet.google.js') ?>"></script>
<script type="text/javascript" src="<?= site_url('application/views/common/leaflet.bing.js') ?>"></script>

<!-- TinyMCE HTML editor -->
<script type="text/javascript" src="<?= site_url() ?>/application/views/common/tinymce/js/tinymce/tinymce.min.js"></script>

<!-- color picker -->
<link rel="stylesheet" media="screen" type="text/css" href="<?= site_url() ?>/application/views/common/colorpicker/css/colorpicker.css" />
<script type="text/javascript" src="<?= site_url() ?>/application/views/common/colorpicker/js/colorpicker.js"></script>

<!-- AjaxForm, we now have file uploads and plain AJAX can't handle it -->
<script type="text/javascript" src="<?= site_url() ?>/application/views/common/jquery.ajaxform.js"></script>

<!-- code specific to this page -->
<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/settings.js"></script>
<script type="text/javascript">
var BING_API_KEY = <?= json_encode( $siteconfig['bing_api_key'] ) ?>;

var BASEMAP_TYPE   = <?= json_encode( $siteconfig['basemap_type'] ) ?>;
var BASEMAP_XYZURL = <?= json_encode( $siteconfig['basemap_xyzurl'] ) ?>;
</script>

<style type="text/css">
textarea {
    width:5in;
    height:3in;
}

td,th {
    vertical-align:top;
}

th {
    padding-top:1em;
    font-size:16pt;
}

.ui-icon-info {
    display:inline-block;
    margin-left:1em;
}

#bbox_map_canvas {
    width:6.0in;
    height:4.5in;
}

div.basemap_option {
    margin-left:1.5em;
}
</style>



<form id="settingsform" action="<?= site_url() ?>administration/ajax_save_settings" method="post" enctype="multipart/form-data">
    <div class="tabs container" style="width:100%; padding:0;">
        <ul>
            <li><a href="#settingsform_tab_basic">Web Site Title &amp; Theme</a></li>
            <li style="display:none;"><a href="#settingsform_tab_html">HTML Web Pages</a></li><!-- hack they decided there's no website anymore! trivial details, right? but they'll want it back! -->
            <li><a href="#settingsform_tab_extent">Map Services</a></li>
            <li><a href="#settingsform_tab_icons">Map Icons</a></li>
            <li><a href="#settingsform_tab_mobile">Mobile Site</a></li>
        </ul>
        <div id="settingsform_tab_basic">
            <p>These basic settings define the title of your website and of your organization. Also defined is a general color theme for the desktop browser version of the website.</p>

            <table class="table-condensed">
            <tr>
                <td>Web Site Title <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This title appears in the browser's navigation tab and in bookmarks. In most other places, you would manually enter the title like any other website content."></div></td>
                <td><input type="text" name="title" size="50" maxlength="50" value="<?= htmlspecialchars( $siteconfig['title'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Web Site Theme <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Select a color theme for your website."></div></td>
                <td>
                    <?= form_dropdown('jquitheme', $themes, $siteconfig['jquitheme'] ) ?>
                    <br/>
                    <img id="jquitheme_swatch" src="about:blank;" title="This is an example of the selected color scheme." />
                </td>
            </tr>
            <tr>
                <td>Organization Name <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="In the bottom-left of pages, this organization name will appear as a hyperlink to your main website."></div></td>
                <td><input type="text" name="company_name" size="50" maxlength="50" value="<?= htmlspecialchars( $siteconfig['company_name'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Organization Web Site URL<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="In the bottom-left of pages, this hyperlink will be shown so visitors can get to your main website."></div></td>
                <td><input type="text" name="company_url" size="50" maxlength="50" value="<?= htmlspecialchars( $siteconfig['company_url'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Time Zone<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="What time zone should be used to report dates and times? This is particularly important for events."></div></td>
                <td><?= form_dropdown('timezone', $timezones, $siteconfig['timezone'] ) ?></td>
            </tr>
            </table>
        </div>
        <div id="settingsform_tab_html" style="display:none;"><!-- hack they decided there's no website anymore! trivial details, right? but they'll want it back! -->
            <p>This panel allows you to define the HTML content for various pages of your website, such as the opening page.</p>

            <table class="table-condensed">
            <tr>
                <td>HTML for the front page <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This HTML will form the content of the front page of your site at <?= htmlentities(site_url()) ?>"></div></td>
                <td>
                    <textarea name="html_frontpage"><?= htmlspecialchars($siteconfig['html_frontpage']) ?></textarea>
                    </td>
            </tr>
            <tr>
                <td>HTML for the &quot;About&quot; page <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This HTML will form the content of the About page."></div></td>
                <td>
                    <textarea name="html_about"><?= htmlspecialchars($siteconfig['html_about']) ?></textarea>
                </td>
            </tr>
            </table>
        </div>
        <div id="settingsform_tab_extent">
            <p>This panel allows you to define map settings, such as the area of interest and a Bing Maps API key for geocoding.</p>
            <p>Note that the area given may not exactly match the map as it appears on other computer screens.</p>

            <table class="table-condensed">
            <tr>
                <td>Bing Maps API Key <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="To use the Bing basemaps and address services, you need a Bing Maps API Key."></div></td>
                <td><input type="text" name="bing_api_key" size="80" maxlength="100" value="<?= htmlspecialchars( $siteconfig['bing_api_key'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Google Maps API Key <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="To use the Google basemaps and address services beyond certain restrictions, you need a Google Maps API Key."></div></td>
                <td><input type="text" name="google_api_key" size="80" maxlength="100" value="<?= htmlspecialchars( $siteconfig['google_api_key'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Basemap <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="The underlying map can be your choice of Google Maps, Bing Maps, or any publicly-accessible tile service using XYZ-compatible format (TMS, WMS-T, Mapbox)."></div></td>
                <td>
                    <!-- the radiobox values are connected to the basemap_option boxes below; see the basemap_type event handler setup in settings.js -->
                    <!-- these are also used here on the admin panel for the map; see settings.js where MAP is set up, and top of settings.phtml where some JS vars are exposed -->
                    <label><input type="radio" name="basemap_type" value="googlestreets"     <?= $siteconfig['basemap_type'] == 'googlestreets'   ? 'checked' : '' ?> /> Google Maps, Streets</label><br/>
                    <div class="basemap_option" data-basemaptype="googlestreets">
                    </div>

                    <label><input type="radio" name="basemap_type" value="googleterrain"     <?= $siteconfig['basemap_type'] == 'googleterrain'   ? 'checked' : '' ?> /> Google Maps, Terrain</label><br/>
                    <div class="basemap_option" data-basemaptype="googleterrain">
                    </div>

                    <label><input type="radio" name="basemap_type" value="googlesatellite"   <?= $siteconfig['basemap_type'] == 'googlesatellite' ? 'checked' : '' ?> /> Google Maps, Satellite</label><br/>
                    <div class="basemap_option" data-basemaptype="googlesatellite">
                    </div>

                    <label><input type="radio" name="basemap_type" value="bingstreets"       <?= $siteconfig['basemap_type'] == 'bingstreets'     ? 'checked' : '' ?> /> Bing Maps, Streets</label><br/>
                    <div class="basemap_option" data-basemaptype="bingstreets">
                        In order to use Bing Maps you must have an API key entered; see the preceeding option <i>Bing Maps API Key</i>.
                        <br/>
                        A Bing API key is highly recommended in any case, for looking up addresses and getting directions.
                    </div>

                    <label><input type="radio" name="basemap_type" value="bingsatellite"     <?= $siteconfig['basemap_type'] == 'bingsatellite'   ? 'checked' : '' ?> /> Bing Maps, Satellite</label><br/>
                    <div class="basemap_option" data-basemaptype="bingsatellite">
                        In order to use Bing Maps you must have an API key entered; see the preceeding option <i>Bing Maps API Key</i>.
                        <br/>
                        A Bing API key is highly recommended in any case, for looking up addresses and getting directions.
                    </div>

                    <label><input type="radio" name="basemap_type" value="xyz"               <?= $siteconfig['basemap_type'] == 'xyz'             ? 'checked' : '' ?> /> XYZ Tiles (TMS, WMS-T, Mapbox)</label><br/>
                    <div class="basemap_option" data-basemaptype="xyz">
                        <input type="text" name="basemap_xyzurl" value="<?= $siteconfig['basemap_xyzurl'] ?>" size="80" maxlength="150" />
                        <br/>
                        The &quot;URL template&quot; used by Leaflet to load XYZ tiles.<br/>
                        Use {x} {y} and {z} as placeholders for the tile ordinates.<br/>
                        Use {s} as a placeholder for a random selection of subdomains 'a', 'b', 'c', and 'd' (optional).<br/>
                        Example and default: &nbsp; <i>http://{s}.tiles.mapbox.com/v3/greeninfo.map-fdff5ykx/{z}/{x}/{y}.jpg</i>
                    </div>
                </td>
            </tr>
            <tr>
                <td>Address Services (Geocoder) <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Select which geocoder you want to be used when viewing the map (Desktop) and when doing a Near Address search (mobile). Note that both providers have terms of use, which you should read!"></div></td>
                <td>
                    <label><input type="radio" name="preferred_geocoder" value="bing" <?= $siteconfig['preferred_geocoder']=='bing'?'checked':'' ?> /> Bing Maps API</label> <br/>
                    <div style="margin-left:1.5em;">
                        Using Bing for address services, requires that you have a Bing Maps API key entered above.<br/>
                        To get a Bing Maps API key, <a href="http://msdn.microsoft.com/en-us/library/ff428642.aspx" target="_blank">follow these instructions</a>.<br/>
                        You may also want to review the <a href="http://www.microsoft.com/maps/product/terms.html" target="_blank">Bing Maps API Terms of Use</a>
                    </div>
                    <label><input type="radio" name="preferred_geocoder" value="google" <?= $siteconfig['preferred_geocoder']=='google'?'checked':'' ?> /> Google Maps API</label> <br/>
                    <div style="margin-left:1.5em;">
                        Use of Google Maps address service is subject to <a href="https://developers.google.com/maps/terms" target="_blank">Terms of Use</a> which you may want to review.<br/>
                        One such restriction, is that <i>you must also use a Google Basemap</i>.<br/>
                        If you have Google For Work and an API key (which may relieve some of these restrictions),<br/>
                        you may enter it into <i>Google Maps API Key</i> above, and it will be included with your Google Maps API service calls.
                    </div>
                </td>
            </tr>
            <tr>
                <td>Starting Map View <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Pan and zoom the map to define the area displayed when a visitor first visits the Map page."></div></td>
                <td>
                    <input type="text" name="bbox_w" value="<?= $siteconfig['bbox_w'] ?>" style="display:none;" />
                    <input type="text" name="bbox_s" value="<?= $siteconfig['bbox_s'] ?>" style="display:none;" />
                    <input type="text" name="bbox_e" value="<?= $siteconfig['bbox_e'] ?>" style="display:none;" />
                    <input type="text" name="bbox_n" value="<?= $siteconfig['bbox_n'] ?>" style="display:none;" />
                    <div id="bbox_map_canvas"></div>
                    <input type="text" id="geocode" size="58" placeholder="Search for your city or neighborhood" /> <input type="button" id="geocode_go" value="Search" />
                </td>
            </tr>
            <tr>
                <td>Metric or Imperial? <div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Report distances in metric (kilometers) or Imperial (miles) ?"></div></td>
                <td><?= form_dropdown('metric_units', array('0'=>'Imperial (miles)', '1'=>'Metric (kilometers)'), $siteconfig['metric_units'] ) ?></td>
            </tr>
            </table>
        </div>
        <div id="settingsform_tab_icons">
            <table class="table-condensed">
            <tr>
                <td>Place Markers<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This marker will be used to indicate places on the map. This should be a PNG file, no more than 25 x 45 in size."></div></td>
                <td>
                    <img src="<?= site_url() ?>/mobile/image/marker_place" />
                    <br/>
                    <?= $siteconfig['place_marker_width'] ?> x <?= $siteconfig['place_marker_height'] ?>
                    <br/>
                    <br/>
                    If you want to replace the current marker, select the file here.<br/>
                    This should be a PNG file, no more than 25 x 45 in size.<br/>
                    Tip: Use a transparent background, or a solid rectangular shape.<br/>
                    <input type="file" name="place_marker" size="50" />
                    <br/>
                    Glow Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="When info is being shown for a place, the marker has a glow effect added to it. Pick the color for this glow."></div> <input type="text" class="color" style="color:white;" name="place_markerglowcolor" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['place_markerglowcolor'] ) ?>" />
                </td>
            </tr>
            <tr>
                <td>Event Location Markers<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This marker will be used to indicate event locations on the map. This should be a PNG file, no more than 25 x 45 in size."></div></td>
                <td>
                    <img src="<?= site_url() ?>/mobile/image/marker_event" />
                    <br/>
                    <?= $siteconfig['event_marker_width'] ?> x <?= $siteconfig['event_marker_height'] ?>
                    <br/>
                    <br/>
                    If you want to replace the current marker, select the file here.<br/>
                    This should be a PNG file, no more than 25 x 45 in size.<br/>
                    Tip: Use a transparent background, or a solid rectangular shape.<br/>
                    <input type="file" name="event_marker" size="50" />
                    <br/>
                    Glow Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="When info is being shown for an event, the marker has a glow effect added to it. Pick the color for this glow."></div> <input type="text" class="color" style="color:white;" name="event_markerglowcolor" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['event_markerglowcolor'] ) ?>" />
                </td>
            </tr>
            <tr>
                <td>Event &amp; Place Markers<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This marker will be used to indicate a location with both EVents and Places. This should be a PNG file, no more than 25 x 45 in size."></div></td>
                <td>
                    <img src="<?= site_url() ?>/mobile/image/marker_both" />
                    <br/>
                    <?= $siteconfig['both_marker_width'] ?> x <?= $siteconfig['both_marker_height'] ?>
                    <br/>
                    <br/>
                    If you want to replace the current marker, select the file here.<br/>
                    This should be a PNG file, no more than 25 x 45 in size.<br/>
                    Tip: Use a transparent background, or a solid rectangular shape.<br/>
                    <input type="file" name="both_marker" size="50" />
                </td>
            </tr>
            <tr>
                <td>GPS Marker<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This marker will be used to show the user's location. This should be a PNG file, no more than 25 x 45 in size."></div></td>
                <td>
                    <img src="<?= site_url() ?>/mobile/image/marker_gps" />
                    <br/>
                    <?= $siteconfig['marker_gps_width'] ?> x <?= $siteconfig['marker_gps_height'] ?>
                    <br/>
                    <br/>
                    If you want to replace the current marker, select the file here.<br/>
                    This should be a PNG file, no more than 25 x 45 in size.<br/>
                    Tip: Use a transparent background, or a solid rectangular shape.<br/>
                    <input type="file" name="mobile_marker_gps" size="50" />
                    <br/>
                </td>
            </tr>
            </table>
        </div>
        <div id="settingsform_tab_mobile">
            <p>Users on mobile devices will automatically be redirected to <a target="_blank" href="<?= site_url() ?>/mobile">the mobile site</a>. Use this panel to set colors and other options for the mobile site.</p>

            <table class="table-condensed">
            <tr>
                <td colspan="2"><h3>Colors</h3></td>
            </tr>
            <tr>
                <td>General BG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="The global background color. This is used site-wide, except as overridden below."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_bgcolor" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_bgcolor'] ) ?>" /></td>
            </tr>
            <tr>
                <td>General FG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="The global foreground (text) color. This is used site-wide, except as overridden below."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_fgcolor" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_fgcolor'] ) ?>" /></td>
            </tr>

            <tr>
                <td>Button BG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Default buttons: Background color. This means most buttons and selector widgets."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_buttonbgcolor1" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_buttonbgcolor1'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Button FG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Default buttons: Foreground (text) color. This means most buttons and selector widgets."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_buttonfgcolor1" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_buttonfgcolor1'] ) ?>" /></td>
            </tr>

            <tr>
                <td>Alternate BG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Alternate buttons: Background color. Alternate buttons are a few special ones on the Search panel."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_buttonbgcolor2" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_buttonbgcolor2'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Alternate FG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Alternate buttons: Foreground (text) color. Alternate buttons are a few special ones on the Search panel."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_buttonfgcolor2" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_buttonfgcolor2'] ) ?>" /></td>
            </tr>

            <tr>
                <td>Highlight BG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Highlight: Background color. Highlights include special alert buttons, as well as the currently-selected tab."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_alertbgcolor" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_alertbgcolor'] ) ?>" /></td>
            </tr>
            <tr>
                <td>Highlight FG Color<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="Highlight: Foreground (text) color. Highlights include special alert buttons, as well as the currently-selected tab."></div></td>
                <td><input type="text" class="color" style="color:white;" name="mobile_alertfgcolor" size="7" maxlength="7" value="<?= htmlspecialchars( $siteconfig['mobile_alertfgcolor'] ) ?>" /></td>
            </tr>

            <tr>
                <td colspan="2"><h3>Branding</h3></td>
            </tr>
            <tr>
                <td>Main Logo<div class="ui-icon ui-icon-info" data-toggle="tooltip" title="This logo will be shown at the top-center of the landing page (which is also the search page). The size should be approximately 230 x 120. Tip: Using a logo wider than 320px or taller than 150px may not look good on small devices."></div></td>
                <td>
                    <img src="<?= site_url() ?>/mobile/image/logo" />
                    <br/>
                    <?= $siteconfig['mobile_logo_width'] ?> x <?= $siteconfig['mobile_logo_height'] ?>
                    <br/>
                    <br/>
                    If you want to replace the current logo, select the file here.<br/>
                    The size should be approximately 230 x 120.<br/>
                    Using a logo wider than 320px or taller than 150px may not look good on small devices.<br/>
                    Tip: The background should be transparent, or else complementary to your background color.<br/>
                    <input type="file" name="mobile_logo" size="50" />
                </td>
            </tr>

            </table>
        </div>

    </div><!-- end of tabset -->

    <div style="text-align:center; margin-top:2em;">
        <div class="btn-group">
            <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-thumbs-up"></span> Save Changes</button>
        </div>
    </div>
</form>


<br/>
</div>



<? $this->load->view('administration/footer.phtml') ?>
