<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/users.js"></script>

<div class="btn-group btn-group-rightfloater">
    <button type="button" class="btn ui-state-focus" id="button_new"><span class="glyphicon glyphicon-certificate"></span> New</button>
</div>


<table class="table table-striped table-hover table-condensed table-bordered" style="width:100%;">
<tr>
    <th>Username</th>
    <th>Status</th>
</tr>
<?php foreach ($users as $user) { ?>
<tr>
    <td><a href="<?= site_url("administration/user/{$user->id}") ?>"><?= $user->username ?></a></td>
    <td><?= $levels[$user->level] ?></td>
</tr>
<?php } ?>
</table>




<div class="dialog" id="dialog_new">
<form action="javascript:void(0);">
    <table>
    <tr>
        <td>E-mail</td>
        <td><input type="text" name="username" maxlength="50" style="width:3in;" placeholder="E-mail address" /></td>
    </tr>
    <tr>
        <td>Password</td>
        <td><input type="text" name="password" maxlength="50" style="width:3in;" placeholder="Password" /></td>
    </tr>
    <tr>
        <td>Status</td>
        <td><?= form_dropdown('level', $levels, 1) ?></td>
    </tr>
    </table>
</form>
</div>



<? $this->load->view('administration/footer.phtml') ?>
