<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/users.js"></script>




<div class="tabs container" style="width:100%; padding:0;">
    <ul>
        <li><a href="#tab_users">User Accounts</a></li>
    </ul>
    <div id="tab_users">

        <div class="btn-group btn-group-rightfloater">
            <button type="button" class="btn ui-state-focus" id="button_new"><span class="glyphicon glyphicon-certificate"></span> New</button>
        </div>

        <h4>User Accounts</h4>
<!--
        <p>This lists the user profiles on this website. Users with <i>Manager</i> or <i>Administrator</i> status can log in to this administration panel and make changes to the website. At this time <i>Website</i> accounts have no function; hypothetically they could login to the website and save profiles or favorites or something.</p>
-->
        <p>These user accounts can login to this administration portal to manage your site.</p>

        <table class="table table-striped table-hover table-condensed table-bordered sortable" style="width:100%;">
        <thead>
        <tr>
            <th>Username</th>
            <!-- <th>Status</th> -->
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user) { ?>
        <tr>
            <td><a href="<?= site_url("administration/user/{$user->id}") ?>"><?= $user->username ?></a></td>
            <!-- <td><?= $levels[$user->level] ?></td> -->
        </tr>
        <?php } ?>
        </tbody>
        </table>

    </div>
</div>




<div class="dialog" id="dialog_new">
<form action="javascript:void(0);">
    <table>
    <tr>
        <td>E-mail</td>
        <td><input type="text" name="username" maxlength="50" style="width:3in;" placeholder="E-mail address" /></td>
    </tr>
    <tr>
        <td>Password</td>
        <td><input type="text" name="password" maxlength="50" style="width:3in;" placeholder="Password" /></td>
    </tr>
    <tr style="display:none;"><!-- hack: hide this until they decide what user levels they want, and whether they should be used -->
        <td>Status</td>
        <!-- <td><?= form_dropdown('level', $levels, 1) ?></td> --><!-- hack: hide this until they decide what user levels they want, and whether they should be used; show the hidden field instead-->
        <td><input type="hidden" name="level" value="1" /></td>
    </tr>
    </table>
</form>
</div>



<? $this->load->view('administration/footer.phtml') ?>
