<? $this->load->view('administration/header.phtml') ?>

<script type="text/javascript" src="<?= site_url() ?>/application/views/administration/user.js"></script>


<div class="container">
    <br/>

    <form action="javascript:void(0);" id="editform">
    <input type="hidden" name="id" value="<?= $user->id ?>" />
    <table class="table-condensed table-bordered">
        <tr>
            <td>E-mail address</td>
            <td><input type="text" name="username" value="<?= $user->username ?>" size="50" maxlength="50" /></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="text" name="password" /><br/><small>only if you want to change it</small></td>
        </tr>

        <?php if ($user->isSuper()) { ?>
        <tr>
            <td>Status</td>
            <td><?= $levels[USER_LEVEL_ADMIN] ?></td>
        </tr>
        <?php } else { ?>
        <tr>
            <td>Status</td>
            <td><?= form_dropdown('level', $levels, $user->level) ?></td>
        </tr>
        <?php } ?>

        <tr>
            <td></td>
            <td>
                <div class="btn-group">
                <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-thumbs-up"></span> Save Changes</button>
                </div>
            </td>
        </tr>
    </table>
    </form>

</div>


<div class="container">
<?php if (! $user->isSuper()) { ?>
    <form action="<?= site_url('administration/user_delete') ?>" method="post" style="text-align:right;">
        <input type="hidden" name="id" value="<?= $user->id ?>" />
        <div class="btn-group">
        <button type="submit" class="btn ui-state-focus"><span class="glyphicon glyphicon-trash"></span> Delete</button>
        </div>
    </form>
<?php } else { ?>
    <br/>
<?php } ?>
</div>

<? $this->load->view('administration/footer.phtml') ?>
