<html>
<head>
</head>
<body>

<form action="<?= site_url('administration') ?>" method="post">
    <p>Please note the following, then proceed to administration.</p>
    <table>
    <tr><td>Admin username:</td><td><b><?= $admin_username ?></b></td></tr>
    <tr><td>Admin password:</td><td><b><?= $admin_password ?></b></td></tr>
    <tr><td colspan="2"><input type="submit" value="Proceed to administration" /></td></tr>
    </table>
</form>

</body>
</html>