<!DOCTYPE html>
<html>
<head>
    <title><?= $this->siteconfig->get('title') ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- jQuery and jQuery Mobile -->
    <script type="text/javascript" src="<?= site_url() ?>/application/views/common/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="<?= site_url() ?>/application/views/mobile/jquerymobile-1.4.2/jquery.mobile-1.4.2.css" />
    <script src="<?= site_url() ?>/application/views/mobile/jquerymobile-1.4.2/jquery.mobile-1.4.2.min.js"></script>
    <script type="text/javascript" src="<?= site_url() ?>/application/views/common/jquery.sort.js"></script>

    <!-- Leaflet map framework -->
    <link rel="stylesheet" href="<?=site_url()  ?>/application/views/common/leaflet-0.6.4/leaflet.css" />
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="<?=site_url()  ?>/application/views/common/leaflet-0.6.4/leaflet.ie.css" />
    <![endif]-->
    <script src="<?=site_url()  ?>/application/views/common/leaflet-0.6.4/leaflet.js"></script>

    <script src="<?=site_url()  ?>/application/views/mobile/leaflet.custommobilecontrols.js"></script>
    <link rel="stylesheet" href="<?=site_url()  ?>/application/views/mobile/leaflet.custommobilecontrols.css" />

    <script src="<?=site_url()  ?>/application/views/common/leaflet.markercluster/leaflet.markercluster.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<?=site_url()  ?>/application/views/common/leaflet.markercluster/MarkerCluster.css" />
    <link rel="stylesheet" type="text/css" href="<?=site_url()  ?>/application/views/common/leaflet.markercluster/MarkerCluster.Default.css" />

    <script type="text/javascript">
    var BASE_URL = <?= json_encode(site_url()) ?>;

    var BING_API_KEY = <?= json_encode( $this->siteconfig->get('bing_api_key') ) ?>;

    var DISTANCE_UNITS = <?= json_encode($metric ? 'km' : 'mi') ?>;

    var START_W = <?= $this->siteconfig->get('bbox_w') ?>;
    var START_S = <?= $this->siteconfig->get('bbox_s') ?>;
    var START_E = <?= $this->siteconfig->get('bbox_e') ?>;
    var START_N = <?= $this->siteconfig->get('bbox_n') ?>;
    var START_X = <?= ( $this->siteconfig->get('bbox_w') + $this->siteconfig->get('bbox_e') ) /2 ?>;
    var START_Y = <?= ( $this->siteconfig->get('bbox_s') + $this->siteconfig->get('bbox_n') ) /2 ?>;
    </script>

    <!-- sitewide styling overriding the selected theme and providing common code & style to the front-facing site -->
    <link rel="stylesheet" type="text/css" href="<?= site_url() ?>/application/views/mobile/index.css" />
    <script type="text/javascript" src="<?= site_url() ?>/application/views/mobile/index.js"></script>
</head>
<body>


<div data-role="page" id="page-search">
    <form action="javascript:void(0);">
        <div class="center">
            <img src="<?= site_url() ?>/application/views/mobile/mobile-logo.png" />
        </div>

        <div class="outside_area" id="search-outsidearea">
            You seem to be outside the supported area.
            <br/>
            Using <i>My current location</i> may result in no matches,
            <br/>
            and the map may not show anything close to you.
        </div>

        <h3 class="center">Find Parks and Recreation Near:</h3>
        <select name="location">
            <option value="gps">My current location</option>
            <option value="address">Address</option>
        </select>
        <input type="text" name="address" placeholder="enter address" class="center" />
        <input type="hidden" name="lat" />
        <input type="hidden" name="lng" />

        <a data-role="button" href="#page-search-settings" data-icon="carat-d" data-iconpos="right">Find an activity (optional)</a>

        <button name="search-go" data-icon="search" data-iconpos="right" data-theme="b">Search</button>

        <hr/>

        <h3 class="center">OR:</h3>
        <button name="search-browse-map" data-icon="map" data-iconpos="right">Browse the Map</button>
    </form>
</div>


<div data-role="page" id="page-search-settings">
    <div data-role="header" data-position="inline">
        <a href="#page-search" data-role="button" data-icon="arrow-l">Apply</a>
        <h2>Search Options</h2>
    </div>

    <div data-role="collapsible-set" data-theme="a" data-content-theme="b">
        <div data-role="collapsible">
            <h2>Activities &amp; Amenities</h2>
            <div data-role="controlgroup" data-mini="true">
                <?php foreach ($place_categories as $catid=>$catname) { ?>
                <label><input type="checkbox" name="categories" value="<?= $catid ?>" /> <?= $catname ?></label>
                <?php } ?>
            </div>
        </div>
        <div data-role="collapsible">
            <h2>Age</h2>
            <div data-role="controlgroup" data-mini="true">
                <label><input type="checkbox" name="agegroup" value="1" /> Infant &amp; Toddler (age 0-2)</label>
                <label><input type="checkbox" name="agegroup" value="2" /> Pre-School (age 3-4)</label>
                <label><input type="checkbox" name="agegroup" value="3" /> Youth / Teen (age 6-18)</label>
                <label><input type="checkbox" name="agegroup" value="4" /> Adult (age 18-54)</label>
                <label><input type="checkbox" name="agegroup" value="5" /> Senior (55 &amp; up)</label>
                <label><input type="checkbox" name="agegroup" value="0" /> All Ages</label>
            </div>
        </div>
        <div data-role="collapsible">
            <h2>Gender</h2>
            <div data-role="controlgroup" data-mini="true">
                <label><input type="checkbox" name="gender" value="1" /> Male</label>
                <label><input type="checkbox" name="gender" value="2" /> Female</label>
                <label><input type="checkbox" name="gender" value="0" /> Either/Both</label>
            </div>
        </div>
        <div data-role="collapsible">
            <h2>When</h2>
            <div data-role="controlgroup" data-mini="true">
                <label><input type="checkbox" name="eventdays" value="0" /> Today</label>
                <label><input type="checkbox" name="eventdays" value="6" /> This Week</label>
                <label><input type="checkbox" name="eventdays" value="30" /> Within The Next Month</label>
                <label><input type="checkbox" name="weekdays" value="mon" /> On Mondays</label>
                <label><input type="checkbox" name="weekdays" value="tue" /> On Tuesdays</label>
                <label><input type="checkbox" name="weekdays" value="wed" /> On Wednesdays</label>
                <label><input type="checkbox" name="weekdays" value="thu" /> On Thursdays</label>
                <label><input type="checkbox" name="weekdays" value="fri" /> On Fridays</label>
                <label><input type="checkbox" name="weekdays" value="sat" /> On Saturdays</label>
                <label><input type="checkbox" name="weekdays" value="sun" /> On Sundays</label>
            </div>
        </div>
    </div>
</div>



<div data-role="page" id="page-search-results-places" class="page-results">
    <div class="ui-grid-b search-results-navbar">
        <div class="ui-block-a"><img src="<?= site_url() ?>/application/views/mobile/jquerymobile-1.4.2/images/icons-png/home-white.png" /> <a href="#page-search">Home</a></div>
        <div class="ui-block-b active"><a href="#page-search-results-places">Parks &amp;<br/>Rec Centers</a></div>
        <div class="ui-block-c"><a href="#page-search-results-events">Events &amp;<br/>Activities</a></div>
    </div>
    <div class="ui-grid-b">
        <div class="ui-block-a"><a href="#page-search-settings" data-role="button" data-inline="true" data-mini="true" data-icon="search" data-theme="b">Find</a></div>
        <div class="ui-block-b"></div>
        <div class="ui-block-c right"><a href="#page-map" data-role="button" data-icon="map" data-inline="true" data-mini="true">Map</a></div>
    </div>

    <div id="page-search-results">
        <ul data-role="listview" id="page-search-results-places-list" data-filter="true">
        </ul>
    </div>
</div>



<div data-role="page" id="page-search-results-events" class="page-results">
    <div class="ui-grid-b search-results-navbar">
        <div class="ui-block-a"><img src="<?= site_url() ?>/application/views/mobile/jquerymobile-1.4.2/images/icons-png/home-white.png" /> <a href="#page-search">Home</a></div>
        <div class="ui-block-b"><a href="#page-search-results-places">Parks &amp;<br/>Rec Centers</a></div>
        <div class="ui-block-c active"><a href="#page-search-results-events">Events &amp;<br/>Activities</a></div>
    </div>
    <div class="ui-grid-b">
        <div class="ui-block-a"><a href="#page-search-settings" data-role="button" data-inline="true" data-mini="true" data-icon="search" data-theme="b">Find</a></div>
        <div class="ui-block-b"></div>
        <div class="ui-block-c right"><a href="#page-map" data-role="button" data-icon="map" data-inline="true" data-mini="true">Map</a></div>
    </div>

    <div id="page-search-results">
        <ul data-role="listview" id="page-search-results-events-list" data-filter="true">
        </ul>
    </div>
</div>



<div data-role="page" id="page-map">
    <div>
        <div id="map_canvas">
            <div class="outside_area" id="map-outsidearea">
                You seem to be outside
                <br/>
                of the supported area.
            </div>
            <div id="map_infopanel">
                <a href="javascript:void(0);" data-role="button" data-icon="delete" data-iconpos="notext" data-inline="true" data-mini="true"></a><!--this X closes the panel, see initMapInfoPanel() -->
                <div data-type="place">
                    <h3 data-field="name"></h3>
                    <p data-field="desc"></p>
                    <a data-field="url" target="_blank" href="about:blank">More Info</a>
                    <p>Categories: <span data-field="categories"></span></p>
                </div>
                <div data-type="eventlocation">
                    <h3 data-field="event.name"></h3>
                    <p data-field="event.datetime"></p>
                    <p>
                        <span data-field="location.title"></span>
                        <br/>
                        <span data-field="location.subtitle"></span>
                    </p>
                    <a data-field="event.url" target="_blank" href="about:blank">More Info</a>
                </div>
            </div>
        </div>

        <div data-role="panel" id="panel-map-settings" data-position="right" data-display="overlay">
            <h2 style="margin:0;">
                <a href="#page-map" data-rel="close" data-role="button" data-icon="delete" data-iconpos="notext" data-inline="true" data-mini="true"></a> Map Settings
            </h2>

            <div data-role="controlgroup" data-type="horizontal" data-mini="true">
                <label><input type="radio" name="basemap" value="terrain" checked /> Terrain</label>
                <label><input type="radio" name="basemap" value="photo" /> Satellite</label>
                <label><input type="radio" name="basemap" value="topo" /> Topo</label>
            </div>
        </div>
    </div>
</div>





</body>
</html>
